# Generated by Django 4.0.5 on 2022-06-29 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75)),
                ('last_name', models.CharField(max_length=75)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'maile'), ('f', 'female')], max_length=20)),
                ('email_id', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('is_department_head', models.BooleanField()),
                ('postition', models.IntegerField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collage.department')),
            ],
        ),
    ]
