# Generated by Django 4.0.5 on 2022-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='project_id',
            field=models.ManyToManyField(related_name='employees', to='collage.project'),
        ),
    ]
